# Generated by Django 6.0.7 on 2026-08-09 05:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_limit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='budget_user_active_idx'), models.Index(fields=['user', 'start_date', 'end_date'], name='budget_user_dates_idx'), models.Index(fields=['user', 'category', 'is_active'], name='budget_user_category_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('budget_limit__gt', 0)), name='budget_limit_gt_zero'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='budget_end_date_gte_start_date')],
            },
        ),
    ]
