# Generated by Django 6.0.7 on 2026-08-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-start_date', '-created_at']},
        ),
    ]
