# Generated by Django 6.0.7 on 2026-08-19 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('savings_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('category_totals', models.JSONField(blank=True, default=dict)),
                ('budget_metrics', models.JSONField(blank=True, default=dict)),
                ('behaviour_metrics', models.JSONField(blank=True, default=dict)),
                ('trend_metrics', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='snapshot_user_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'month', 'year'), name='unique_analysis_snapshot_user_month'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='analysis_snapshot_valid_month')],
            },
        ),
    ]
