# Generated by Django 6.0.7 on 2026-08-20 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recurringtransaction',
            name='recurring_transaction_amount_gt_zero',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recurring_source',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-transaction_time', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_recurring_generated',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_time'], name='transaction_user_time_idx'),
        ),
        migrations.DeleteModel(
            name='RecurringTransaction',
        ),
    ]
