# Generated by Django 6.0.7 on 2026-08-21 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_recurringtransaction_recurring_transaction_amount_gt_zero_and_more'),
    ]

    operations = [
    ]



DEFAULT_CATEGORIES = [
    # Income categories.
    {
        "name": "Salary",
        "category_type": "Income",
    },
    {
        "name": "Bonus",
        "category_type": "Income",
    },
    {
        "name": "Freelance",
        "category_type": "Income",
    },
    {
        "name": "Other income",
        "category_type": "Income",
    },
    {
        "name": "Interest income",
        "category_type": "Income",
    },
    {
        "name": "Investment returns",
        "category_type": "Income",
    },
    {
        "name": "Gift received",
        "category_type": "Income",
    },
    {
        "name": "Refund",
        "category_type": "Income",
    },

    # Expense need categories.
    {
        "name": "Household",
        "category_type": "Need",
    },
    {
        "name": "Health",
        "category_type": "Need",
    },
    {
        "name": "Transportation",
        "category_type": "Need",
    },
    {
        "name": "Education",
        "category_type": "Need",
    },
    {
        "name": "Groceries",
        "category_type": "Need",
    },
    {
        "name": "Fuel",
        "category_type": "Need",
    },
    {
        "name": "Rent",
        "category_type": "Need",
    },
    {
        "name": "Vehicle",
        "category_type": "Need",
    },
    {
        "name": "Electricity",
        "category_type": "Need",
    },
    {
        "name": "Internet",
        "category_type": "Need",
    },
    {
        "name": "Insurance",
        "category_type": "Need",
    },
    {
        "name": "Loan",
        "category_type": "Need",
    },
    {
        "name": "Interest",
        "category_type": "Need",
    },
    {
        "name": "Taxes",
        "category_type": "Need",
    },
    {
        "name": "Utilities",
        "category_type": "Need",
    },
    {
        "name": "Mobile phone",
        "category_type": "Need",
    },
    {
        "name": "Childcare",
        "category_type": "Need",
    },
    {
        "name": "Pet care",
        "category_type": "Need",
    },

    # Expense want categories.
    {
        "name": "Entertainment",
        "category_type": "Want",
    },
    {
        "name": "Gift",
        "category_type": "Want",
    },
    {
        "name": "Restaurant",
        "category_type": "Want",
    },
    {
        "name": "Shopping",
        "category_type": "Want",
    },
    {
        "name": "Clothing",
        "category_type": "Want",
    },
    {
        "name": "Travel",
        "category_type": "Want",
    },
    {
        "name": "Personal care",
        "category_type": "Want",
    },
    {
        "name": "Subscriptions",
        "category_type": "Want",
    },
    {
        "name": "Donations",
        "category_type": "Want",
    },

    # Savings categories.
    {
        "name": "Investment",
        "category_type": "Savings",
    },
    {
        "name": "Emergency fund",
        "category_type": "Savings",
    },
    {
        "name": "Retirement",
        "category_type": "Savings",
    },
]


def add_default_categories(apps, schema_editor):
    Category = apps.get_model(
        "transactions",
        "Category",
    )

    for category_data in DEFAULT_CATEGORIES:
        category, created = (
            Category.objects.get_or_create(
                user=None,
                name=category_data["name"],
                defaults={
                    "category_type": (
                        category_data["category_type"]
                    ),
                    "is_default": True,
                },
            )
        )

        if not created:
            changed = False

            if category.category_type != (
                category_data["category_type"]
            ):
                category.category_type = (
                    category_data["category_type"]
                )
                changed = True

            if not category.is_default:
                category.is_default = True
                changed = True

            if category.user_id is not None:
                category.user = None
                changed = True

            if changed:
                category.save(
                    update_fields=[
                        "category_type",
                        "is_default",
                        "user",
                    ]
                )


def remove_default_categories(
    apps,
    schema_editor,
):
    Category = apps.get_model(
        "transactions",
        "Category",
    )

    category_names = [
        category["name"]
        for category in DEFAULT_CATEGORIES
    ]

    Category.objects.filter(
        user=None,
        is_default=True,
        name__in=category_names,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.RunPython(
            add_default_categories,
            remove_default_categories,
        ),
    ]