# Generated by Django 6.0.7 on 2026-08-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_recurringtransaction_recurring_transaction_amount_gt_zero_and_more'),
        ('transactions', '0003_add_default_categories'),
    ]

    operations = [
    ]
