# Generated by Django 6.0.7 on 2026-08-09 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_text', models.TextField()),
                ('insight_type', models.CharField(choices=[('Anomaly', 'Anomaly'), ('Budget_Pacing', 'Budget Pacing'), ('Trend', 'Trend')], max_length=30)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_month', models.IntegerField(blank=True, null=True)),
                ('reference_year', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_start_date', models.DateField(blank=True, null=True)),
                ('analysis_end_date', models.DateField(blank=True, null=True)),
                ('generation_model', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
