# Generated by Django 6.0.7 on 2026-08-19 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_summary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('summary_text', models.TextField()),
                ('insights', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Insight',
        ),
        migrations.AddIndex(
            model_name='aisummary',
            index=models.Index(fields=['user', 'year', 'month'], name='ai_summary_user_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='aisummary',
            constraint=models.UniqueConstraint(fields=('user', 'month', 'year'), name='unique_ai_summary_user_month'),
        ),
        migrations.AddConstraint(
            model_name='aisummary',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='ai_summary_valid_month'),
        ),
    ]
